// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createIcon } from '../createIcons';
import type { IconVariants } from '../types';

const burgerMenuFour: IconVariants = {
  Stroke: [['path', { d: 'M4 9H20M4 14H20M4 19H20M4 4H20', stroke: 'currentColor', key: 's0' }]],
  Solid: [['path', { d: 'M4 9H20M4 14H20M4 19H20M4 4H20', stroke: 'currentColor', key: 's0' }]],
  Contrast: [['path', { d: 'M4 9H20M4 14H20M4 19H20M4 4H20', stroke: 'currentColor', key: 's0' }]],
  'Duo Stroke': [
    ['path', { d: 'M4 14H20M4 4H20', stroke: 'currentColor', opacity: 0.28, key: 'd0' }],
    ['path', { d: 'M4 9H20M4 19H20', stroke: 'currentColor', key: 'd1' }],
  ],
  'Duo Solid': [
    ['path', { d: 'M4 9H20M4 14H20M4 19H20M4 4H20', stroke: 'currentColor', key: 's0' }],
  ],
};

export const BurgerMenuFour = createIcon('burger-menu-four', burgerMenuFour);
export default BurgerMenuFour;
