// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createIcon } from '../createIcons';
import type { IconVariants } from '../types';

const burgerMenuThree: IconVariants = {
  Stroke: [['path', { d: 'M4 12H20M4 18H20M4 6H20', stroke: 'currentColor', key: 's0' }]],
  Solid: [['path', { d: 'M4 12H20M4 18H20M4 6H20', stroke: 'currentColor', key: 's0' }]],
  Contrast: [['path', { d: 'M4 12H20M4 18H20M4 6H20', stroke: 'currentColor', key: 's0' }]],
  'Duo Stroke': [
    ['path', { d: 'M4 12H20', stroke: 'currentColor', opacity: 0.28, key: 'd0' }],
    ['path', { d: 'M4 18H20M4 6H20', stroke: 'currentColor', key: 'd1' }],
  ],
  'Duo Solid': [['path', { d: 'M4 12H20M4 18H20M4 6H20', stroke: 'currentColor', key: 's0' }]],
};

export const BurgerMenuThree = createIcon('burger-menu-three', burgerMenuThree);
export default BurgerMenuThree;
