// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createIcon } from '../createIcons';
import type { IconVariants } from '../types';

const godlyWebsite: IconVariants = {
  Stroke: [['path', { d: 'M13.5 2L7.5 12H16.5L10.5 22', stroke: 'currentColor', key: 's0' }]],
  Solid: [['path', { d: 'M13.5 2L7.5 12H16.5L10.5 22', stroke: 'currentColor', key: 's0' }]],
  Contrast: [['path', { d: 'M13.5 2L7.5 12H16.5L10.5 22', stroke: 'currentColor', key: 's0' }]],
  'Duo Stroke': [
    [
      'path',
      { d: 'M13.5 2L7.5 12H16.5L10.5 22', stroke: 'currentColor', opacity: 0.28, key: 'd0' },
    ],
    ['path', { d: 'M7.5 12H16.5', stroke: 'currentColor', key: 'd1' }],
  ],
  'Duo Solid': [['path', { d: 'M13.5 2L7.5 12H16.5L10.5 22', stroke: 'currentColor', key: 's0' }]],
};

export const GodlyWebsite = createIcon('godly-website', godlyWebsite);
export default GodlyWebsite;
