// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createIcon } from '../createIcons';
import type { IconVariants } from '../types';

const graphChartGantt: IconVariants = {
  Stroke: [
    [
      'path',
      {
        d: 'M21 21H7C4.79086 21 3 19.2091 3 17V3M7 7H10M10 12H17M17 17H20',
        stroke: 'currentColor',
        key: 's0',
      },
    ],
  ],
  Solid: [
    [
      'path',
      {
        d: 'M21 21H7C4.79086 21 3 19.2091 3 17V3M7 7H10M10 12H17M17 17H20',
        stroke: 'currentColor',
        key: 's0',
      },
    ],
  ],
  Contrast: [
    [
      'path',
      {
        d: 'M21 21H7C4.79086 21 3 19.2091 3 17V3M7 7H10M10 12H17M17 17H20',
        stroke: 'currentColor',
        key: 's0',
      },
    ],
  ],
  'Duo Stroke': [
    [
      'path',
      {
        d: 'M21 21H7C4.79086 21 3 19.2091 3 17V3',
        stroke: 'currentColor',
        opacity: 0.28,
        key: 'd0',
      },
    ],
    ['path', { d: 'M7 7H10M10 12H17M17 17H20', stroke: 'currentColor', key: 'd1' }],
  ],
  'Duo Solid': [
    [
      'path',
      {
        d: 'M21 21H7C4.79086 21 3 19.2091 3 17V3M7 7H10M10 12H17M17 17H20',
        stroke: 'currentColor',
        key: 's0',
      },
    ],
  ],
};

export const GraphChartGantt = createIcon('graph-chart-gantt', graphChartGantt);
export default GraphChartGantt;
