// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createIcon } from '../createIcons';
import type { IconVariants } from '../types';

const plusDefault: IconVariants = {
  Stroke: [
    ['path', { d: 'M12 19V12M12 12V5M12 12L5 12M12 12L19 12', stroke: 'currentColor', key: 's0' }],
  ],
  Solid: [
    ['path', { d: 'M12 19V12M12 12V5M12 12L5 12M12 12L19 12', stroke: 'currentColor', key: 's0' }],
  ],
  Contrast: [
    ['path', { d: 'M12 19V12M12 12V5M12 12L5 12M12 12L19 12', stroke: 'currentColor', key: 's0' }],
  ],
  'Duo Stroke': [
    ['path', { d: 'M5 12H19', stroke: 'currentColor', opacity: 0.28, key: 'd0' }],
    ['path', { d: 'M12 19V5', stroke: 'currentColor', key: 'd1' }],
  ],
  'Duo Solid': [
    ['path', { d: 'M12 19V12M12 12V5M12 12L5 12M12 12L19 12', stroke: 'currentColor', key: 's0' }],
  ],
};

export const PlusDefault = createIcon('plus-default', plusDefault);
export default PlusDefault;
